language: java
jdk: oraclejdk8

script:
  - mvn verify

services:
  - mysql
before_install:
  - mysql -u root -e 'CREATE DATABASE gutenberg;'
  - mysql -u root -e 'CREATE TABLE gutenberg.books(id int(11) PRIMARY KEY NOT NULL, title varchar(255) DEFAULT NULL);'