language: java
jdk: oraclejdk8

script:
  - mvn verify

services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS gutenberg;'
  - mysql -u root gutenberg < src/test/gutenberg_2017-05-27.sql