language: java
jdk: oraclejdk8

script:
  - mvn verify

services:
  - mysql
  - mongodb

before_install:
  - mysql -u root -e 'CREATE DATABASE gutenberg;'
  - mysql -u root gutenberg < gutenberg.sql
  - mongo use soft-semeter-1
  - mongo db.createCollection("gutenberg")