language: java
jdk: oraclejdk8

script:
  - mvn verify

services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE gutenberg';
  - mysql UPDATE user SET password=PASSWORD('root') WHERE user='root';
  - mysql FLUSH PRIVILEGES;
  - mysql -u root -p gutenberg < 'src/main/files/databaseExports/gutenberg_2017-05-27.sql';
