language: java
jdk: oraclejdk8

script:
  - mvn verify

services:
  - mysql
before_install:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -u root -e 'CREATE DATABASE gutenberg;'
  - mysql -u root gutenberg < gutenberg.sql