language: java
jdk: oraclejdk8

script:
  - mvn verify

services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE gutenberg;'
  - mysql -u root gutenberg < curl https://github.com/bigstepdenmark/gutenbergdb/blob/master/src/test/gutenberg_2017-05-27.sql