language: java
jdk: oraclejdk8

script:
  - mvn verify

services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE gutenberg';
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -u root -p gutenberg < 'src/main/files/databaseExports/gutenberg_2017-05-27.sql';
