language: java
jdk: oraclejdk8

script:
  - mvn verify

services:
  - mysql
before_install:
  - mysql -u root -e 'CREATE DATABASE gutenberg;'
  - mysql SET PASSWORD FOR 'root'@'localhost' = PASSWORD('root')
  - mysql -u root gutenberg < gutenberg.sql